syms q1 q2 q3 c1 c2 r s c3 m a b q_2 h x y z p

x = 1
y = 1
z = 1
JAC = [(x - 1)*(h*y*(z - 1) + p*z*(y - 1) - y*z*(h + p)) + x*(h*y*(z - 1) + p*z*(y - 1) - y*z*(s - c1 + q1*r) - (a*q1 + b*(c3 - q3 + s))*(y - 1)*(z - 1) + y*(b*(c3 - q3 + s) + a*q1*r)*(z - 1) + z*(y - 1)*(c3 + q1 - q3 + 2*s) - y*z*(h + p)) - x*(y*z*(s - c1 + q1*r) + (a*q1 + b*(c3 - q3 + s))*(y - 1)*(z - 1) - y*(b*(c3 - q3 + s) + a*q1*r)*(z - 1) - z*(y - 1)*(c3 + q1 - q3 + 2*s)) + y*z*(s - c1 + q1*r) + (a*q1 + b*(c3 - q3 + s))*(y - 1)*(z - 1) - y*(b*(c3 - q3 + s) + a*q1*r)*(z - 1) - z*(y - 1)*(c3 + q1 - q3 + 2*s), x*(x*((b*(c3 - q3 + s) + a*q1*r)*(z - 1) - (a*q1 + b*(c3 - q3 + s))*(z - 1) + z*(c3 + q1 - q3 + 2*s) - z*(s - c1 + q1*r)) - (b*(c3 - q3 + s) + a*q1*r)*(z - 1) + (a*q1 + b*(c3 - q3 + s))*(z - 1) + (x - 1)*(p*z - z*(h + p) + h*(z - 1)) - z*(c3 + q1 - q3 + 2*s) + z*(s - c1 + q1*r)),                                                                                                                                                                                                     x*(x*((y - 1)*(c3 + q1 - q3 + 2*s) - (a*q1 + b*(c3 - q3 + s))*(y - 1) + y*(b*(c3 - q3 + s) + a*q1*r) - y*(s - c1 + q1*r)) - (y - 1)*(c3 + q1 - q3 + 2*s) + (x - 1)*(h*y - y*(h + p) + p*(y - 1)) + (a*q1 + b*(c3 - q3 + s))*(y - 1) - y*(b*(c3 - q3 + s) + a*q1*r) + y*(s - c1 + q1*r));
                                                                                                                                                                                                                                                                                                                                                            -y*(q_2*z - (b*c2 - a*q2*r)*(z - 1) + y*((b*c2 - a*q2*r)*(z - 1) - q_2*z + z*(q_2 - c2 + q2*r)) - z*(q_2 - c2 + q2*r) + (y - 1)*(q_2*z + z*(h - q_2) - h*(z - 1))), x*z*(q_2 - c2 + q2*r) - y*(x*z*(q_2 - c2 + q2*r) - q_2*z*(x - 1) + x*(b*c2 - a*q2*r)*(z - 1)) - (y - 1)*(q_2*z*(x - 1) - h*x*(z - 1) + x*z*(h - q_2)) - q_2*z*(x - 1) - y*(x*z*(q_2 - c2 + q2*r) - h*x*(z - 1) + x*(b*c2 - a*q2*r)*(z - 1) + x*z*(h - q_2)) + x*(b*c2 - a*q2*r)*(z - 1),                                                                                                                                                                                                                                                                                                                          -y*(y*(x*(q_2 - c2 + q2*r) - q_2*(x - 1) + x*(b*c2 - a*q2*r)) + q_2*(x - 1) - x*(q_2 - c2 + q2*r) + (y - 1)*(x*(h - q_2) - h*x + q_2*(x - 1)) - x*(b*c2 - a*q2*r));
                                                                                                                                                                                                                                                                                                                        z*(z*(y*(c3 + p + s) - (y - 1)*(c3 + p + s) + y*(c3 - q3 + s) - (y - 1)*(c3 + q3 + s)) + (m*y - y*(m - q3))*(z - 1) - y*(c3 + p + s) + (y - 1)*(c3 + p + s) - y*(c3 - q3 + s) + (y - 1)*(c3 + q3 + s)),                                                                                                                                        z*((z - 1)*(x*(m + q3) - x*(m - q3) - (m + q3)*(x - 1) + m*(x - 1)) + x*(c3 + q3 + s) - z*(x*(c3 + q3 + s) - x*(c3 - q3 + s)) - x*(c3 - q3 + s)), z*(m*y*(x - 1) - (m + q3)*(x - 1)*(y - 1) + y*(x - 1)*(c3 + p + s) + x*y*(c3 - q3 + s) - x*(y - 1)*(c3 + q3 + s) - (x - 1)*(y - 1)*(c3 + p + s) - x*y*(m - q3) + x*(m + q3)*(y - 1)) + (z - 1)*(m*y*(x - 1) - (m + q3)*(x - 1)*(y - 1) - x*y*(m - q3) + x*(m + q3)*(y - 1)) + z*(y*(x - 1)*(c3 + p + s) + x*y*(c3 - q3 + s) - x*(y - 1)*(c3 + q3 + s) - (x - 1)*(y - 1)*(c3 + p + s)) - y*(x - 1)*(c3 + p + s) - x*y*(c3 - q3 + s) + x*(y - 1)*(c3 + q3 + s) + (x - 1)*(y - 1)*(c3 + p + s)]
 


eig(JAC)